webtalk_init -webtalk_dir C:/Users/Emelin/vivado_projects/UART/UART/RS422_PROJECT/RS422_PROJECT.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb  1 07:16:46 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8fbbda15-3b15-4b28-8157-2efa9be6a9a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9691a75b43ae400d96d08556fe4522d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3125050 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14564_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1965941297 -regid "" -xml C:/Users/Emelin/vivado_projects/UART/UART/RS422_PROJECT/RS422_PROJECT.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Emelin/vivado_projects/UART/UART/RS422_PROJECT/RS422_PROJECT.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Emelin/vivado_projects/UART/UART/RS422_PROJECT/RS422_PROJECT.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
